server:
  port: 3000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/learnjdbc
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1